Add crossfade transition
adrielcafe/voyager pull request #286
Opened 2023-12-23 14:49 UTC by Revxrsal

This PR adds a basic crossfade transition for navigation, as I felt it's missing.

2023-12-24 17:31 UTC, DevNatan requested changes
Binary compatibility check failed please run `gradle apidump` to regenerate .api with your code. Also, can you provide a GIF using this transition on one of our samples, for us to include in the docs

2023-12-26 20:50 UTC, Revxrsal commented
I made the function public. I've tried running `gradle apidump`, but it gave me an error about local.properties missing. I admittedly  feel it's unnecessary to go through the whole setup procedure and install what's probably worth 1GB+ dependencies for all the platforms that Voyager supports, just to add a simple function 😅 

Here's a GIF:
![Crossfade](https://github.com/adrielcafe/voyager/assets/26172484/94b2262e-5cbe-45a8-9bcb-451887fff233)

2024-01-12 14:46 UTC, Revxrsal commented
Hey @DevNatan o/ I know you're busy, but could you please let me know if anything's left here? I use voyager in so many projects and this would save me lots of time 🙆‍♂️

2024-01-19 15:42 UTC, DevNatan approved these changes

2024-01-19 21:59 UTC, merged